version: '3'
services:
  node-app:
    build: 
      context: . #Dockefile directory
      args: 
        NODE_ENV: development
    volumes:
      #Local directory / Inner container directory
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev